---
- name: Download Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-armv7.tar.gz
    dest: /tmp/node_exporter-1.3.1.linux-armv7.tar.gz

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter-1.3.1.linux-armv7.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move Node Exporter binary to /usr/local/bin
  command: mv /tmp/node_exporter-1.3.1.linux-armv7/node_exporter /usr/local/bin/node_exporter

- name: Set permissions for Node Exporter binary
  file:
    path: /usr/local/bin/node_exporter
    mode: '0755'

- name: Create systemd service file for Node Exporter
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=nobody
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=default.target
    mode: '0644'

- name: Reload systemd to recognize Node Exporter service
  systemd:
    daemon_reload: yes

- name: Start Node Exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes

- name: Ensure Node Exporter service is running
  systemd:
    name: node_exporter
    state: started
    enabled: yes
