---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install common dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - vim
    - htop
    - net-tools
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Set timezone to UTC
  timezone:
    name: UTC

- name: Create a directory for k3s configuration
  file:
    path: /etc/rancher/k3s
    state: directory
    owner: root
    group: root
    mode: 0755

# Disable swap for k3s
- name: Disable swap
  command: swapoff -a

# Remove swap entries from /etc/fstab to prevent re-enabling on reboot
- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^\s*([^#\s]\S+)\s+\S+\s+swap\s+'
    replace: '#\1 swap'

# k3s doesn't require br_netfilter but it's a good practice to ensure it's loaded
- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Ensure br_netfilter module is loaded on boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter

- name: Set sysctl parameters for k3s networking
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Restart systemd-sysctl service
  systemd:
    name: systemd-sysctl
    state: restarted
    enabled: yes

- name: Ensure sysctl parameters are set
  command: sysctl --system

- name: Set hostname for each node
  hostname:
    name: "{{ inventory_hostname }}"

- name: Get PARTUUID from blkid
  command: blkid -s PARTUUID -o value /dev/mmcblk0p2
  register: partuuid_result
  become: true

- name: Ensure cgroup settings are correct in cmdline.txt
  copy:
    content: "{{ [
      'console=serial0,115200 console=tty1 root=PARTUUID=' + partuuid_result.stdout,
      'rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles',
      'cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 cgroup_no_v1=all systemd.unified_cgroup_hierarchy=1'
      ] | join(' ') }}"
    dest: /boot/firmware/cmdline.txt
  become: true
  notify: Reboot Raspberry Pi
