apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/logs"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "cronworkflows", "workflowtemplates"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get", "list", "update", "patch"]
  - apiGroups: [""]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "create", "delete", "update"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["", "argoproj.io"]
    resources: ["workflowtaskresults", "workflowartifactgctasks", "workflowtasksets", "ClusterWorkflowTemplates"]
    verbs: ["get", "list", "watch", "delete", "create", "update", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-role-binding
subjects:
  - kind: ServiceAccount
    name: argo
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: argo-role
  apiGroup: rbac.authorization.k8s.io
