- name: Reboot Raspberry Pi
  become: true
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible to apply kernel parameters for cgroup memory."
    pre_reboot_delay: 10
    post_reboot_delay: 30
    reboot_timeout: 300
