name: Code Linting Check

on:
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    name: Ansible Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint Ansible files
        run: |
          if [ ! -d ansible/ ]; then
            echo "::warning::Ansible directory not found. Skipping Ansible linting."
            exit 0  # Exit gracefully if directory not found
          else
            sudo apt update
            sudo apt install python3-pip
            pip3 install ansible ansible-lint
            find ansible/ -type f -name '*.yml' -exec ansible-lint {} +
          fi

  helm-lint:
    name: Helm Chart Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint Helm charts
        run: |
          if [ ! -d helm/ ]; then
            echo "::warning::Helm directory not found. Skipping Helm chart linting."
            exit 0  # Exit gracefully if directory not found
          else
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            chmod 700 get_helm.sh
            ./get_helm.sh
            find helm/ -type f -name '*.yml' -exec helm lint {} +
          fi

  bash-lint:
    name: Bash Script Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ShellCheck
        run: sudo apt install shellcheck

      - name: Lint Bash scripts
        id: bash-lint
        run: |
          find . -type f -name '*.sh' -exec shellcheck {} +

  check-newlines:
    name: Check Newlines
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for newline at end of files and fail if missing
        id: newline-check
        run: |
          files_missing_newline=$(find . -type f ! -path './.git/*' -exec sh -c 'tail -c1 < "$1" | read -r _ || echo "$1"' sh {} \;)
          if [ -n "$files_missing_newline" ]; then
            echo "::error::One or more files are missing a newline character at the end."
            echo "$files_missing_newline"
           exit 1
          fi
